name: waterwin_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  dartz: ^0.10.1
  device_info_plus: ^11.2.0
  equatable: ^2.0.7
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_iconly: ^1.0.2
  flutter_keyboard_visibility: ^6.0.0
  flutter_local_notifications: ^18.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  go_router: ^14.6.2
  google_mobile_ads: ^5.2.0
  injectable: ^2.5.0
  intl: ^0.20.1
  lottie: ^3.2.0
  pinput: ^5.0.0
  retrofit: ^4.4.1
  shared_preferences: ^2.3.4
  shimmer: ^3.0.0
  unity_ads_plugin: ^0.3.22

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  floor_generator: ^1.5.0
  retrofit_generator: ^9.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/svg/information/
    - assets/images/svg/homepage/
    - assets/images/svg/point/
    - assets/images/svg/homepage/bottles/
    - assets/images/png/
    - assets/images/jpg/
    - assets/images/jpg/onboarding/
    - assets/images/png/onboarding/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400 
        - asset: assets/fonts/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist-Black.ttf
          weight: 900